name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup TeXLive Action
        uses: teatimeguest/setup-texlive-action@v3.3.1
        with:
          packages: full

      - name: Build Draft
        run: |
          make draft
          cp my_paper.pdf my_paper_draft.pdf

      - name: Build Final
        run: make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: |
            my_paper.pdf
            my_paper_draft.pdf
