name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Install TeXLive
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install texlive-full
      #     sudo apt-get install texlive-lang-english

      - name: Cache TeXLive
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: texlive-full texlive-lang-english

      - name: Check Environment Variables
        run: |
          echo "TEXHOME=$TEXHOME"
          echo "PATH=$PATH"
          ls -l

      - name: Build Draft
        run: |
          make draft
          cp my_paper.pdf my_paper_draft.pdf

      - name: Build Final
        run: make

      - name: Find and Zip Log Files
        if: failure()
        run: |
          find . -name "*.log" -print0 | xargs -0 zip logs.zip

      - name: Upload Log Files
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: latex-logs
          path: logs.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: |
            my_paper.pdf
            my_paper_draft.pdf
