name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GnuPlot
        run: |
          sudo apt-get install gnuplot

      - name: Install TexLive-Full
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: scheme-full

      - name: Install Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Tikz externalize does not work with cached TexLive
      - name: Set No-Externalize Flag
        run: |
          touch no_externalize.flag

      - name: Check Environment Variables
        run: |
          echo "TEXHOME=$TEXHOME"
          echo "PATH=$PATH"
          ls -l

      - name: Build Final
        run: |
          make
          PROJECT_NAME=$(sed -n 's/^PROJECT_NAME = //p' project_name)
          cp ${PROJECT_NAME}.pdf final.pdf

      - name: Build Draft
        run: |
          make draft
          PROJECT_NAME=$(sed -n 's/^PROJECT_NAME = //p' project_name)
          cp ${PROJECT_NAME}.pdf draft.pdf

      - name: Build Tectonic
        run: |
          make tectonic
          PROJECT_NAME=$(sed -n 's/^PROJECT_NAME = //p' project_name)
          cp ${PROJECT_NAME}.pdf tectonic-final.pdf

      - name: Build Draft Tectonic
        run: |
          make tectonic-draft
          PROJECT_NAME=$(sed -n 's/^PROJECT_NAME = //p' project_name)
          cp ${PROJECT_NAME}.pdf tectonic-draft.pdf

      - name: Find and Zip Log Files
        if: failure()
        run: |
          find . -name "*.log" -print0 | xargs -0 zip logs.zip

      - name: Upload Log Files
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: latex-logs
          path: logs.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: |
            draft.pdf
            tectonic-draft.pdf
            final.pdf
            tectonic-final.pdf
