name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup TeXLive Action
        uses: teatimeguest/setup-texlive-action@v3.3.1
        with:
          packages: scheme-full

      - name: Check Environment Variables
        run: |
          echo "TEXHOME=$TEXHOME"
          echo "PATH=$PATH"
          ls -l

      - name: Build Draft
        run: |
          make draft
          cp my_paper.pdf my_paper_draft.pdf

      # If the build fails, output the log file
      - name: Upload Log File
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: my_paper.log

      - name: Build Final
        run: make

      # If the build fails, output the log file
      - name: Upload Log File
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: my_paper.log

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: |
            my_paper.pdf
            my_paper_draft.pdf
